{{- if eq .Values.mode "cronjob" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ocync.fullname" . }}
  labels:
    {{- include "ocync.labels" . | nindent 4 }}
  {{- with .Values.cronJobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        {{- include "ocync.podTemplate" . | nindent 8 }}
{{- end }}
