{{- if eq .Values.mode "watch" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocync.fullname" . }}
  labels:
    {{- include "ocync.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ocync.selectorLabels" . | nindent 6 }}
  template:
    {{- include "ocync.podTemplate" . | nindent 4 }}
{{- end }}
