{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ocync.fullname" . }}
  labels:
    {{- include "ocync.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.externalSecrets.target.name | default (include "ocync.fullname" .) }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | default "Owner" }}
  {{- with .Values.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
