{{- if eq .Values.mode "job" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ocync.fullname" . }}
  labels:
    {{- include "ocync.labels" . | nindent 4 }}
spec:
  template:
    {{- include "ocync.podTemplate" . | nindent 4 }}
{{- end }}
