{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ocync.fullname" . }}
  labels:
    {{- include "ocync.labels" . | nindent 4 }}
spec:
  provider: {{ required "ocync: secretProviderClass.provider is required when secretProviderClass.enabled is true (one of: aws, azure, gcp, vault)" .Values.secretProviderClass.provider | quote }}
  parameters:
    {{- toYaml .Values.secretProviderClass.parameters | nindent 4 }}
  {{- with .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
