{{- if .Values.serviceAccount.create -}}
{{- $wiAnnotations := include "ocync.workloadIdentity.serviceAccountAnnotations" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ocync.serviceAccountName" . }}
  labels:
    {{- include "ocync.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations $wiAnnotations }}
  annotations:
    {{- with $wiAnnotations }}
    {{- . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
